# Generated by Django 5.1.6 on 2025-02-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Pink', 'Pink'), ('Green', 'Green'), ('Blue', 'Blue'), ('Yellow', 'yellow'), ('Black', 'Black'), ('White', 'White'), ('Beige', 'Beige')], default='RED', max_length=10),
        ),
    ]
